ALTER TABLE clients
ADD COLUMN phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN verification_code VARCHAR(6),
ADD COLUMN verification_expiry TIMESTAMP,
ADD COLUMN reset_code VARCHAR(6),
ADD COLUMN reset_expiry TIMESTAMP;